import { blogPostType } from "./ui/BlogCard";
import { blogImage1 as image1 } from "@/assets";

export const blogPostsData: blogPostType[] = [
  {
    id: 1,
    image_url: image1,
    title: "Title Of Latest Blog",
    description: "Content to be shown in blog...",
    tags: ["Tag #1", "Tag #2", "Tag #3"],
    link_to_post: "/blog/1",
  },
  {
    id: 1,
    image_url: image1,
    title: "Title Of Blog",
    description: "Content to be shown in blog...",
    tags: ["Tag #1", "Tag #2", "Tag #3"],
    link_to_post: "",
  },
  {
    id: 1,
    image_url: image1,
    title: "Title Of Blog",
    description: "Content to be shown in blog...",
    tags: ["Tag #1", "Tag #2", "Tag #3"],
    link_to_post: "",
  },
  {
    id: 1,
    image_url: image1,
    title: "Title Of Blog",
    description: "Content to be shown in blog...",
    tags: ["Tag #1", "Tag #2", "Tag #3"],
    link_to_post: "",
  },
  {
    id: 1,
    image_url: image1,
    title: "Title Of Blog",
    description: "Content to be shown in blog...",
    tags: ["Tag #1", "Tag #2", "Tag #3"],
    link_to_post: "",
  },
  {
    id: 1,
    image_url: image1,
    title: "Title Of Blog",
    description: "Content to be shown in blog...",
    tags: ["Tag #1", "Tag #2", "Tag #3"],
    link_to_post: "",
  },
  {
    id: 1,
    image_url: image1,
    title: "Title Of Blog",
    description: "Content to be shown in blog...",
    tags: ["Tag #1", "Tag #2", "Tag #3"],
    link_to_post: "",
  },
  {
    id: 1,
    image_url: image1,
    title: "Title Of Blog",
    description: "Content to be shown in blog...",
    tags: ["Tag #1", "Tag #2", "Tag #3"],
    link_to_post: "",
  },
  {
    id: 1,
    image_url: image1,
    title: "Title Of Blog",
    description: "Content to be shown in blog...",
    tags: ["Tag #1", "Tag #2", "Tag #3"],
    link_to_post: "",
  },
  {
    id: 1,
    image_url: image1,
    title: "Title Of Blog",
    description: "Content to be shown in blog...",
    tags: ["Tag #1", "Tag #2", "Tag #3"],
    link_to_post: "",
  },
];
